segregation of the components and logic
Jocardan/visual-curriculum pull request #7
Opened 2022-06-02 21:07 UTC by hggmarks

2022-06-02 23:07 UTC, JDaniielC requested changes
Retirar DisciplineGrid de components e colocar em pages/Home/index.tsx, visto que estamos tratando de uma página, não simplesmente de um componente.

2022-06-03 00:37 UTC, JDaniloC commented
It's Ok, but implement the routes is more important.

2022-06-03 00:38 UTC, JDaniloC requested changes
Probably the package-lock will raise a merge conflict, @JDaniielC go merge!

2022-06-03 02:01 UTC, JDaniielC approved these changes

2022-06-03 02:02 UTC, merged